### ISSUE TITLE
Gatling fails at "Generating reports..."

### ISSUE THREAD

**Issue by happyviral** [Logimethods/nats-connector-gatling#2]
I'm new to NATS and Gatling.
I'm evaluating NATS streaming in one of the project.
To evaluate performance, tried with nats-connector-gatling.

I added com.logimethods:nats-connector-gatling_2.11:0.3.0 dependency in maven project.
Simulation is completed, but reports are not generated.

It would be good if you can provide pointers to resolve this. I can provide sample project if required.

Here is the error log:
`Simulation io.nats.NatsInjection completed in 59 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
        at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.UnsupportedOperationException: There were no requests sent during the simulation, reports won't be generated
        at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:48)
        at io.gatling.app.LogFileProcessor.generateReports(RunResultProcessor.scala:64)
        at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:43)
        at io.gatling.app.Gatling.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.start(Gatling.scala:57)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
        at io.gatling.app.Gatling$.main(Gatling.scala:43)
        at io.gatling.app.Gatling.main(Gatling.scala)
        ... 6 more
`

**Comment by laugimethods** [comment]
A sample project would definitely be helpful.

Regards.

**Comment by happyviral** [comment]
Thanks for quick reply.

[nats-gatling-proj.zip](https://github.com/Logimethods/nats-connector-gatling/files/872719/nats-gatling-proj.zip)

I ran "mvn test" command to run simulation.

**Comment by laugimethods** [comment]
@happyviral, I can reproduce your issue.

Actually, the Gatling to Nats Connector was NOT developed to generate reports (a feature that makes sense when we are expecting a response like when calling a Web page), but "only" to generate large number of messages sent to NATS. That's why calling that reports feature fails.

If you want to monitor the number of messages generated, I would suggest having a look at the [SmartMeter Project](https://github.com/Logimethods/smart-meter), which makes use of Graphite/Grafana. To do so, you should use a configuration that looks like [gatling.conf](https://github.com/Logimethods/smart-meter/blob/master/dockerfile-inject/conf/gatling.conf).

Hope I did answer your question.
